#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : init-rdahead
Version  : 17
Release  : 17
URL      : http://localhost/cgit/projects/init-rdahead/snapshot/init-rdahead-17.tar.gz
Source0  : http://localhost/cgit/projects/init-rdahead/snapshot/init-rdahead-17.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: init-rdahead-bin
BuildRequires : musl
BuildRequires : musl-dev
Patch1: fork-four.patch

%description
Read ahead boot files in hyper-v.
Smallest footprint is to  : make smallmusl
Make in debug mode        : make smallmusldebug
If you don't have gcc-musl: make small
If you don't want to strip: make initra

%package bin
Summary: bin components for the init-rdahead package.
Group: Binaries

%description bin
bin components for the init-rdahead package.


%prep
%setup -q -n init-rdahead-17
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1510693130
make V=1  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1510693130
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/initra
/usr/bin/initra-aws
