#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : init-rdahead
Version  : 24
Release  : 30
URL      : http://localhost/cgit/projects/init-rdahead/snapshot/init-rdahead-24.tar.gz
Source0  : http://localhost/cgit/projects/init-rdahead/snapshot/init-rdahead-24.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: init-rdahead-bin
Requires: init-rdahead-license

%description
Read ahead boot files in hyper-v, AWS and desktop.
To build in debug mode:
make DEBUG=1

%package bin
Summary: bin components for the init-rdahead package.
Group: Binaries
Requires: init-rdahead-license

%description bin
bin components for the init-rdahead package.


%package extras
Summary: extras components for the init-rdahead package.
Group: Default

%description extras
extras components for the init-rdahead package.


%package license
Summary: license components for the init-rdahead package.
Group: Default

%description license
license components for the init-rdahead package.


%prep
%setup -q -n init-rdahead-24

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535065997
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1535065997
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/init-rdahead
cp LICENSE %{buildroot}/usr/share/doc/init-rdahead/LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/initra-desktop
/usr/bin/initra
/usr/bin/initra-aws

%files extras
%defattr(-,root,root,-)
/usr/bin/initra-desktop

%files license
%defattr(-,root,root,-)
/usr/share/doc/init-rdahead/LICENSE
